[package]
name = "json"
version = "0.1.0"
authors = ["Frank Murphy <fmurphy@arbor.net>"]

[dependencies.rustc-serialize]
git = "file:///data/rust/rustc-serialize"

[dependencies.libc]
git = "file:///data/rust/libc"

[dependencies.bounded-spsc-queue]
git = "file:///data/rust/bounded-spsc-queue"
